# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'NOVEL' do

pod 'Realm'
pod 'Parse'
pod 'AFNetworking'
pod 'AFOAuth2Manager'
pod 'FBSDKLoginKit'
pod 'ParseFacebookUtilsV4'
pod 'Masonry'
pod 'ParseUI'
pod 'YYWebImage'
pod 'ionicons'
pod 'JSQMessagesViewController'
pod 'DateTools'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ChameleonFramework'

end

target 'NOVELTests' do

end

target 'NOVELUITests' do

end
